### ISSUE TITLE
r3bl_cmdr should not exit after running an example

### ISSUE THREAD

**Issue by shayes12111** [r3bl-org/r3bl-cmdr#14]
*Current:*
The cmdr exits from "App with no layout", et. al. and ends the program

*Desire:*
return to menu screen after exiting App to relaunch other options
pressing "x" to exit app will function as "return"

*Good starting points:*
1. https://github.com/r3bl-org/r3bl-cmdr/blob/main/src/main.rs

**Comment by nazmulidris** [comment]
@shayes12111 good next bug to work on :)
